import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
        }
      `}</style>
      ;
      <Head>
        <title>Polar Bear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bear.ico" />
      </Head>
      {/* <Script src="/script.js" /> */}

      <main className={styles.main}>
        <h1 className={`${styles.title} backColor`}>Polar Bear</h1>

        <Image
          className={styles.backImg}
          src="/pexels-soumil-kumar-735911 (3).jpg"
          alt="keyboard and a hand"
          width={300}
          height={200}
        />

        <p className={styles.description}>A Blog about Coding</p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>JavaScript</h3>
            <p>JavaScript is a programming language.</p>
          </div>
          <div className="blogItem">
            <h3>Java</h3>
            <p>Java is a programming language.</p>
          </div>
          <div className="blogItem">
            <h3>Python</h3>
            <p>Python is a programming language.</p>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
